<!-- PAGE LOGIC -->

<!-- This page aims at displaying the items available in the given category. It's divided in two parts. The first part where we can see the generic item with all its basics characterictics and its description as well, and then the "Hôtel de Vente" part which displayed all the item currently on sales. On this page the user is also allow to directly sell the relevant item  -->

<!-- The idea is to make this page a conditional route with params such as generic item-id. When the page is loaded two things are done, retrieving the generic item and siplay it in the first part of the page, retrieving all the items of this catgery currently on sales -->

<script>
	/* maybe make a JOIN request in SQL to have the generic and all the items on sales at the same time ? */

	import Button from '../../../lib/components/Button.svelte';
	import ItemCard from '../../../lib/components/itemCard.svelte';

	const itemGeneric = {
		weaponid: 645,
		name: 'Hache à Lamelles',
		categorie: 'hache',
		niveau: '176',
		degats_neutre: 'Dommages : 11 à 23 (neutre)',
		degats_neutre_secondaire: null,
		degats_terre: null,
		degats_terre_secondaire: null,
		degats_feu: null,
		degats_feu_secondaire: null,
		degats_air: null,
		degats_air_secondaire: null,
		degats_eau: 'Dommages : 11 à 23 (eau)',
		degats_eau_secondaire: null,
		vol_neutre: null,
		vol_terre: null,
		vol_feu: null,
		vol_air: null,
		vol_eau: null,
		pdv_rendus: null,
		PA_perdus: null,
		PA: null,
		PM: null,
		vitalite: '+201 à 250 en vitalité',
		sagesse: '+21 à 30 en sagesse',
		force: null,
		intelligence: null,
		chance: '+41 à 60 à la chance',
		agilite: null,
		dommage: '+6 à 10 de dommages',
		dommage_pourcent: null,
		initiative: null,
		prospection: '+11 à 20 en prospection',
		coup_critique: '+3 à 4 aux coups critiques',
		PO: '+1 à la portée',
		soins: null,
		invo: null,
		pieges_fixe: null,
		pieges_pourcent: null,
		res_neutre_fixe: null,
		res_neutre_pourcent: null,
		res_terre_fixe: '+6 à 10 de résistance à la terre',
		res_terre_pourcent: null,
		res_feu_fixe: null,
		res_feu_pourcent: null,
		res_eau_fixe: null,
		res_eau_pourcent: null,
		res_air_fixe: null,
		res_air_pourcent: null,
		pods: null,
		renvoi_dommage: null,
		checs_critiques: null,
		chasse: null,
		vole_or: null,
		description:
			"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
		lien_image: '/images/image_hache/images53.svg'
	};

	const itemOnSales = [
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		}
	];

	let visible = 'hidden';

	const handleButtonClick = () => {
		console.log(visible);
		if (visible == 'hidden') {
			visible = 'block';
		} else if (visible == 'block') {
			visible = 'hidden';
		}
		console.log(visible);
	};

	import { slide } from 'svelte/transition';
	import { sineIn } from 'svelte/easing';

	let cardType = 'generic';
</script>

<div class="flex lg:flex-row flex-col">
	{#if visible == 'block'}
		<div class="w-[50%] p-5" transition:slide={{ duration: 350, easing: sineIn }}>
			<div class="card variant-soft-surface space-y-2 transition:fade">
				<header class="card-header text-2xl flex flex-col lg:flex-row items-center justify-between">
					<h2 class="text-xl">Item Générique</h2>
					<Button title={'Vendre'} />
				</header>
				<hr />
				<div class="flex flex-col p-5 items-center">
					<ItemCard item={itemGeneric} {cardType} />
				</div>
			</div>
		</div>
	{/if}
	<div class=" flex flex-col mx-auto p-5 w-full">
		<div class="card variant-soft-surface space-y-2 items-center">
			<header class="card-header text-2xl flex flex-col lg:flex-row items-center justify-between">
				<h2 class="text-xl">Hôtel de Vente</h2>
				<Button title={"Afficher l'objet générique"} on:showGeneric={handleButtonClick} />
			</header>
			<hr />
			<div
				class="flex flex-col lg:flex-row flex-wrap overflow-scroll h-[75vh] space-x-2 flex-grow hide-scrollbar justify-center"
			>
				{#each itemOnSales as item}
					<article class="p-4">
						<ItemCard {item} />
					</article>
				{/each}
			</div>
		</div>
	</div>
</div>
