<!-- Component Logic -->

<!-- This component aims at representing the user hdv. It displays all the items currently on sales by the user  -->

<script>
	import { FileButton } from '@skeletonlabs/skeleton';
	import ItemCard from './itemCard.svelte';

	const title = 'Bienvenue sur Dofus Market';
	const date = '17 Janvier 2023 ';
	const itemHdv = [
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		},
		{
			user_weapon_id: 4,
			weaponid: 645,
			user_id: 32,
			name: 'Hache à Lamelles',
			type: 'arme',
			categorie: 'hache',
			niveau: '176',
			degats_neutre_before: '20',
			degats_neutre_after: '30',
			degats_neutre_secondaire_before: null,
			degats_neutre_secondaire_after: null,
			degats_terre_before: null,
			degats_terre_after: null,
			degats_terre_secondaire_before: null,
			degats_terre_secondaire_after: null,
			degats_feu_before: null,
			degats_feu_after: null,
			degats_feu_secondaire_before: null,
			degats_feu_secondaire_after: null,
			degats_air_before: null,
			degats_air_after: null,
			degats_air_secondaire_before: null,
			degats_air_secondaire_after: null,
			degats_eau_before: '2',
			degats_eau_after: '3',
			degats_eau_secondaire_before: null,
			degats_eau_secondaire_after: null,
			vol_neutre_before: null,
			vol_neutre_after: null,
			vol_terre_before: null,
			vol_terre_after: null,
			vol_feu_before: null,
			vol_feu_after: null,
			vol_air_before: null,
			vol_air_after: null,
			vol_eau_before: null,
			vol_eau_after: null,
			pdv_rendus: null,
			PA_perdus: null,
			PA: '1',
			PM: null,
			vitalite: '200',
			sagesse: '30',
			force: null,
			intelligence: null,
			chance: '20',
			agilite: null,
			dommage: '10',
			dommage_pourcent: null,
			initiative: null,
			prospection: '10',
			coup_critique: '5',
			PO: '1',
			soins: null,
			invo: null,
			pieges_fixe: null,
			pieges_pourcent: null,
			res_neutre_fixe: null,
			res_neutre_pourcent: null,
			res_terre_fixe: '10',
			res_terre_pourcent: null,
			res_feu_fixe: null,
			res_feu_pourcent: null,
			res_eau_fixe: null,
			res_eau_pourcent: null,
			res_air_fixe: null,
			res_air_pourcent: null,
			pods: null,
			renvoi_dommage: null,
			checs_critiques: null,
			chasse: null,
			vole_or: null,
			description:
				"Les différentes lamelles de cette hache permettent de couper très rapidement le saucisson. Un seul coup de hache permet de couper trois tranches. Pour tuer les ennemis, c'est un peu moins utile, sauf si vous avez l'habitude de les manger en tranches.",
			lien_image: '/images/image_hache/images53.svg',
			price: '20 000',
			discord: null,
			pseudo_ig: 'Mayuji24',
			pseudo: 'pumalicieux59'
		}
	];
</script>

<div class="space-y-2 items-center">
	<!-- 	<header class="text-2xl flex flex-col lg:flex-row justify-between flex-end">
		
	</header> -->

	<section class="p-4 text-justify">
		<div
			class="flex flex-col lg:flex-row flex-wrap overflow-scroll h-[75vh] space-x-2 flex-grow hide-scrollbar justify-center"
		>
			{#each itemHdv as item}
				<article class="p-4">
					<ItemCard {item} />
				</article>
			{/each}
		</div>
	</section>
	<footer class="card-footer">(footer)</footer>
</div>
